const { spawn } = require('child_process');
const { rename, unlink } = require('fs')
const Discord = require ("discord.js");
const db = require('quick.db');
const config = require('./config.json');

module.exports = {
  createdumpy: function(message, executer, isInteraction, file, lines) {
    console.log('\x1b[36m%s\x1b[0m', `Creating dumpy with parameters: FILE: ${file} LINES: ${lines}`);
    const dumpy = spawn('cmd.exe', [`/c java -jar dumpy.jar --lines ${lines} --file ${file}`])
    dumpy.stderr.on('data', (data) => {
      console.log('\x1b[31m%s\x1b[0m', data.toString());
      unlink(file, (err) => {})
      let error = new Discord.MessageEmbed()
      .setTitle(":x: Error")
      .setColor("RED")
      .setDescription("An error occurred whilst generating your dumpy.\nTry again and make sure to provide a working link or upload an attachment.")
      if(isInteraction) {
        return message.editReply({ embeds: [error] })
      } else if (!isInteraction) {
        return message.edit({ embeds: [error] })
      }
    })
    dumpy.stdout.on('data', (data) => {
      data = data.toString()
        console.log('\x1b[36m%s\x1b[0m', data);
        (async () => {
        if(data.includes("Converting")) {
          if(isInteraction) {
            let converting = new Discord.MessageEmbed()
            .setTitle("Dumpy Generator")
            .setColor(config.themecolor)
            .setDescription(`<a:loading:939665977728176168> Converting... Almost finished!`)
            .setFooter(`Generated by: ${executer}`)
            .setTimestamp()
            await message.editReply({ embeds: [converting] })
          } else if (!isInteraction) {
            let converting = new Discord.MessageEmbed()
            .setTitle("Dumpy Generator")
            .setColor(config.themecolor)
            .setDescription(`<a:loading:939665977728176168> Converting... Almost finished!`)
            .setFooter(`Generated by: ${executer}`)
            .setTimestamp()
            await message.edit({ embeds: [converting] })
          }
        }

        if(data.includes("Done.")) {
          let nextnum = db.get('dumpy');
          await rename('dumpy.gif', `dumpys/dumpy${nextnum}.gif`, (err) => {
            if (err) console.log(err);
          });
          let done = new Discord.MessageEmbed()
          .setTitle("Dumpy Generator")
          .setColor(config.themecolor)
          .setDescription(`<a:completed:934404118754263050> Your Dumpy has been generated!\n[Click Here](https://wbmoderation.com/dumpy/dumpy${nextnum}.gif) to download the image **or** if the image didn't load for you.`)
          .setImage(`https://wbmoderation.com/dumpy/dumpy${nextnum}.gif`)
          .setFooter(`Generated by: ${executer}`)
          .setTimestamp()
          db.add('dumpy', 1)
          if(isInteraction) {
            return message.editReply({ embeds: [done] })
          } else if (!isInteraction) {
            return message.edit({ embeds: [done] })
          }

        }
      })();
    })
  }
}
