const config = require('../config.json');
const db = require('quick.db');
const fs = require('fs');
const Discord = require ("discord.js");
const upscale = require('../upscale.js');
const https = require('https')
const { URL, parse } = require('url');
const stringIsAValidUrl = (s, protocols) => {
    try {
        new URL(s);
        const parsed = parse(s);
        return protocols
            ? parsed.protocol
                ? protocols.map(x => `${x.toLowerCase()}:`).includes(parsed.protocol)
                : false
            : true;
    } catch (err) {
        return false;
    }
};
function fileExt(url) {
  return url.split(/[?#]/)[0].split('.').pop().trim();
}

module.exports = {
	name: 'upscaler',
  descrption: '',
  aliases: ['upscale'],
	usage: '<message>',
	args: true,
	async execute(bot, message, args, prefix, commandName, themecolor) {
    if (db.get(`commands.${message.guild.id}.${__filename.replace(`${__dirname}\\`, "").replace(".js", "")}.disabled`)) return message.reply("⛔ This command has been disabled in this server.").then(message => {setTimeout(() => message.delete().catch(error => {}), 10000);});
		if (message.author.bot) return;
		let nofile = new Discord.MessageEmbed()
		.setTitle(":x: Error")
		.setColor("RED")
		.setDescription("No file specified!\nMake sure to provide a link or upload an attachment.")
		let invalidfile = new Discord.MessageEmbed()
		.setTitle(":x: Error")
		.setColor("RED")
		.setDescription("Invalid file!\nMake sure to provide a working link or upload an attachment.\n*Note: Multiple links **will not** work.*")
		let file;
		if(!args[0] && !message.attachments.first()) return message.channel.send({ embeds: [nofile]});
		if(args[0]) {
			file = args[0]
		} else if (message.attachments.first()) {
			file = message.attachments.first().attachment
		}
		if(!stringIsAValidUrl(file, ['http', 'https'])) return message.channel.send({ embeds: [invalidfile]});
		let ext = fileExt(file)
		let filename = db.get('upscale')
		let executer = message.author.tag
		let downloading = new Discord.MessageEmbed()
		.setTitle("Image Upscaler")
		.setColor(themecolor)
		.setDescription(`<a:loading:939665977728176168> Downloading your file...`)
		.setFooter(`Generated by: ${executer}`)
		.setTimestamp()
		let generating = new Discord.MessageEmbed()
		.setTitle("Image Upscaler")
		.setColor(themecolor)
		.setDescription(`<a:loading:939665977728176168> Upscaling your image...`)
		.setFooter(`Generated by: ${executer}`)
		.setTimestamp()
		let scalemsg = await message.reply({ embeds: [downloading] })
			https.get(file, resp => {
				resp.pipe(fs.createWriteStream(`./upscaler/todo/${filename}.${ext}`));
				resp.on('end', async () => {
					await scalemsg.edit({ embeds: [generating] })
					upscale.upscale(scalemsg, executer, false, filename, ext)
				})
			})



    }
}
